# Pandas Data Selection Practice
"""
This notebook contains beginner-to-intermediate pandas practice questions focused on selecting rows and columns from a customer dataset.

## Skills Practiced

- Selecting rows and columns using `.loc[]`
- Selecting rows and columns using `.iloc[]`
- Filtering data using conditions
- Using multiple conditions with `&`
- Selecting specific columns
- Using string methods such as `.str.startswith()`
- Using `.between()` for inclusive range filtering
- Working with index positions and column labels

## Dataset Context

The dataset contains customer-related information such as customer ID, customer name, age, gender, region, occupation, preferred category,
purchase amount, loyalty program status, and delivery preference.

## Goal

The goal of this practice notebook is to strengthen my understanding of pandas data selection techniques used in real data analysis tasks.

"""

In [1]:
#importing pandas

import pandas as pd

In [2]:
#loading dataset
df=pd.read_csv(r"C:\Users\dhima\Downloads\customer_data_null_values.csv")
df

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
0,1,Alice Thompson,25,Female,North,Engineer,150.75,Yes,Electronics,Express
1,2,Robert Lee,32,Male,South,Teacher,89.50,No,Clothing,Standard
2,3,Emily Chen,28,Female,West,Designer,220.30,Yes,Home Decor,Express
3,4,Michael Patel,45,Male,East,Manager,175.20,No,Electronics,Standard
4,5,Sophia Nguyen,19,Female,North,Student,65.10,Yes,Books,Express
...,...,...,...,...,...,...,...,...,...,...
95,96,Aliyah Holmes,29,Female,North,Analyst,145.60,Yes,Books,Express
96,97,Declan Porter,42,Male,South,Engineer,195.25,No,Electronics,Standard
97,98,Sienna Riley,26,Female,West,Student,85.30,Yes,Home Decor,Express
98,99,Asher Wallace,34,Male,East,Teacher,160.75,No,Clothing,Standard
99,100,Clara Dixon,28,Female,North,Artist,90.40,Yes,Books,Express

In [4]:
# 1. Select all columns for the customer with id 15.
df.iloc[5,:]

id                                6
customer_name          James Wilson
age                              37
gender                         Male
region                        South
occupation                   Doctor
purchase_amount               300.8
loyalty_program                  No
preferred_category         Clothing
delivery_preference        Standard
Name: 5, dtype: object

In [6]:
# 2. Select the first 10 rows and the first 4 columns of the dataset.
df.iloc[1:11,1:5]

     customer_name  age  gender region
1       Robert Lee   32    Male  South
2       Emily Chen   28  Female   West
3    Michael Patel   45    Male   East
4    Sophia Nguyen   19  Female  North
5     James Wilson   37    Male  South
6     Olivia Brown   29  Female   West
7   William Garcia   52    Male   East
8     Ava Martinez   23  Female  North
9       Liam Davis   41    Male  South
10  Isabella Clark   30  Female   West

In [10]:
# 3. Select 'customer_name' and 'purchase_amount' for customers in the North region.
df.loc[df["region"]=="North",["customer_name","purchase_amount"]]

      customer_name  purchase_amount
0    Alice Thompson           150.75
4     Sophia Nguyen            65.10
8      Ava Martinez            95.25
12        Mia Lewis           110.15
16     Amelia Allen            70.20
20     Evelyn Adams            85.30
24   Emily Mitchell           135.60
28   Sofia Phillips           115.30
32  Madison Edwards            90.50
36        Zoey Reed           130.95
40     Riley Brooks            80.15
44       Hannah Cox           125.80
48   Natalie Fisher            95.40
52       Hazel West           140.15
55     Aubrey Myers           130.80
59    Arianna Price           145.15
63   Aurora Jenkins            90.80
67      Clara Wells           140.65
71      Maya Hunter           135.40
75       Lydia Cole            90.25
79    Aria Peterson            85.15
83  Addison Simmons           130.70
87      Autumn Ford           125.20
91       Audrey Fox           135.85
95    Aliyah Holmes           145.60
99      Clara Dixon            90.40

In [17]:
# 4. Select the last 15 rows and columns 3 through 6.
df.iloc[:,3:7].tail(15)

    gender region  occupation  purchase_amount
85  Female   West      Artist            95.50
86    Male   East    Engineer           190.65
87  Female  North     Teacher           125.20
88    Male  South      Doctor           285.75
89  Female   West     Student            80.90
90    Male   East  Consultant           210.30
91  Female  North   Marketing           135.85
92    Male  South     Manager           245.40
93  Female   West    Designer           130.95
94    Male   East      Lawyer           170.50
95  Female  North     Analyst           145.60
96    Male  South    Engineer           195.25
97  Female   West     Student            85.30
98    Male   East     Teacher           160.75
99  Female  North      Artist            90.40

In [18]:
df

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
0,1,Alice Thompson,25,Female,North,Engineer,150.75,Yes,Electronics,Express
1,2,Robert Lee,32,Male,South,Teacher,89.50,No,Clothing,Standard
2,3,Emily Chen,28,Female,West,Designer,220.30,Yes,Home Decor,Express
3,4,Michael Patel,45,Male,East,Manager,175.20,No,Electronics,Standard
4,5,Sophia Nguyen,19,Female,North,Student,65.10,Yes,Books,Express
...,...,...,...,...,...,...,...,...,...,...
95,96,Aliyah Holmes,29,Female,North,Analyst,145.60,Yes,Books,Express
96,97,Declan Porter,42,Male,South,Engineer,195.25,No,Electronics,Standard
97,98,Sienna Riley,26,Female,West,Student,85.30,Yes,Home Decor,Express
98,99,Asher Wallace,34,Male,East,Teacher,160.75,No,Clothing,Standard
99,100,Clara Dixon,28,Female,North,Artist,90.40,Yes,Books,Express

In [5]:

# 5. Select all columns for customers with purchase_amount greater than 200
df.loc[(df["purchase_amount"]>200),:]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
2,3,Emily Chen,28,Female,West,Designer,220.30,Yes,Home Decor,Express
5,6,James Wilson,37,Male,South,Doctor,300.80,No,Clothing,Standard
7,8,William Garcia,52,Male,East,Consultant,200.60,No,Electronics,Standard
13,14,Ethan Walker,38,Male,South,Manager,250.40,No,Clothing,Standard
15,16,Alexander Young,49,Male,East,Doctor,280.95,No,Electronics,Standard
19,20,Henry Green,44,Male,East,Consultant,210.25,No,Home Decor,Standard
25,26,Benjamin Perez,46,Male,South,Manager,230.75,No,Clothing,Standard
29,30,Elijah Campbell,40,Male,South,Doctor,270.85,No,Clothing,Standard
31,32,Logan Evans,43,Male,East,Consultant,205.65,No,Electronics,Standard
35,36,Samuel Morris,48,Male,East,Manager,240.80,No,Electronics,Standard
39,40,Joseph Bell,41,Male,East,Doctor,275.20,No,Electronics,Standard
41,42,Carter Cooper,39,Male,South,Consultant,210.50,No,Clothing,Standard
47,48,Isaac Wood,42,Male,East,Manager,235.25,No,Home Decor,Standard
51,52,Julian Hughes,47,Male,East,Doctor,280.30,No,Electronics,Standard
56,57,Jaxon Kelly,44,Male,South,Consultant,215.45,No,Electronics,Standard
60,61,Connor Griffin,41,Male,South,Manager,240.70,No,Electronics,Standard
64,65,Christian Marshall,48,Male,South,Doctor,285.40,No,Electronics,Standard
68,69,Tristan Sullivan,42,Male,South,Consultant,210.20,No,Electronics,Standard
72,73,Micah Andrews,46,Male,South,Manager,245.75,No,Electronics,Standard
76,77,Isaiah Barnes,43,Male,South,Doctor,280.60,No,Electronics,Standard
80,81,Easton Jordan,40,Male,South,Consultant,215.90,No,Electronics,Standard
84,85,Colton Freeman,44,Male,South,Manager,240.15,No,Electronics,Standard
88,89,Nathan Hart,41,Male,South,Doctor,285.75,No,Electronics,Standard
90,91,Adrian Black,39,Male,East,Consultant,210.30,No,Clothing,Standard
92,93,Caleb Gardner,45,Male,South,Manager,245.40,No,Electronics,Standard

In [3]:
# 6. Select every third row from the first 30 rows and columns 0, 2, and 5.
df.iloc[0:30:3,[0,2,5]]

    id  age occupation
0    1   25   Engineer
3    4   45    Manager
6    7   29    Analyst
9   10   41     Lawyer
12  13   34    Teacher
15  16   49     Doctor
18  19   28   Engineer
21  22   36     Lawyer
24  25   27   Designer
27  28   35   Engineer

In [5]:
# 7. Select 'customer_name', 'age', and 'occupation' for customers with gender 'Female'.
df.loc[(df["gender"]=="Female"),["customer_name","age","occupation","gender"]]

       customer_name  age occupation  gender
0     Alice Thompson   25   Engineer  Female
2         Emily Chen   28   Designer  Female
4      Sophia Nguyen   19    Student  Female
6       Olivia Brown   29    Analyst  Female
8       Ava Martinez   23     Artist  Female
10    Isabella Clark   30  Marketing  Female
12         Mia Lewis   34    Teacher  Female
14    Charlotte Hall   26   Designer  Female
16      Amelia Allen   21    Student  Female
18      Harper Scott   28   Engineer  Female
20      Evelyn Adams   24     Artist  Female
22    Abigail Nelson   31  Marketing  Female
24    Emily Mitchell   27   Designer  Female
26     Avery Roberts   22    Student  Female
28    Sofia Phillips   29    Analyst  Female
30      Grace Parker   26  Marketing  Female
32   Madison Edwards   23     Artist  Female
34     Layla Stewart   30    Teacher  Female
36         Zoey Reed   25   Designer  Female
38   Penelope Morgan   28    Analyst  Female
40      Riley Brooks   24    Student  Female
42       Aria Bailey   27  Marketing  Female
44        Hannah Cox   29   Designer  Female
46     Stella Butler   31   Engineer  Female
48    Natalie Fisher   26     Artist  Female
50     Victoria Gray   24    Student  Female
52        Hazel West   28  Marketing  Female
54      Lillian Ford   30    Teacher  Female
55      Aubrey Myers   27   Designer  Female
57        Ellie Long   23    Student  Female
59     Arianna Price   26    Analyst  Female
61  Savannah Sanders   29  Marketing  Female
63    Aurora Jenkins   24     Artist  Female
65      Skylar Ortiz   27   Designer  Female
67       Clara Wells   30    Analyst  Female
69     Delilah Hayes   25    Student  Female
71       Maya Hunter   28  Marketing  Female
73       Nora Hudson   26   Designer  Female
75        Lydia Cole   24     Artist  Female
77   Eleanor Russell   29    Teacher  Female
79     Aria Peterson   27    Student  Female
81       Lila Murray   25  Marketing  Female
83   Addison Simmons   30   Designer  Female
85    Paisley Pierce   26     Artist  Female
87       Autumn Ford   28    Teacher  Female
89     Brooklyn Dunn   24    Student  Female
91        Audrey Fox   27  Marketing  Female
93       Piper Ellis   25   Designer  Female
95     Aliyah Holmes   29    Analyst  Female
97      Sienna Riley   26    Student  Female
99       Clara Dixon   28     Artist  Female

In [7]:
# 8. Select the 20th to 25th rows (inclusive) and the last 4 columns.
df.iloc[[20,25],:].tail(4)

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
20,21,Evelyn Adams,24,Female,North,Artist,85.30,Yes,Books,Express
25,26,Benjamin Perez,46,Male,South,Manager,230.75,No,Clothing,Standard

In [12]:
# 9. Select all columns for customers enrolled in the loyalty program (loyalty_program = 'Yes').
df.loc[(df["loyalty_program"]=="Yes"),:]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
0,1,Alice Thompson,25,Female,North,Engineer,150.75,Yes,Electronics,Express
2,3,Emily Chen,28,Female,West,Designer,220.30,Yes,Home Decor,Express
4,5,Sophia Nguyen,19,Female,North,Student,65.10,Yes,Books,Express
6,7,Olivia Brown,29,Female,West,Analyst,120.45,Yes,Home Decor,Express
8,9,Ava Martinez,23,Female,North,Artist,95.25,Yes,Books,Express
10,11,Isabella Clark,30,Female,West,Marketing,140.70,Yes,Home Decor,Express
12,13,Mia Lewis,34,Female,North,Teacher,110.15,Yes,Books,Express
14,15,Charlotte Hall,26,Female,West,Designer,130.85,Yes,Home Decor,Express
16,17,Amelia Allen,21,Female,North,Student,70.20,Yes,Books,Express
18,19,Harper Scott,28,Female,West,Engineer,190.50,Yes,Electronics,Express
20,21,Evelyn Adams,24,Female,North,Artist,85.30,Yes,Books,Express
22,23,Abigail Nelson,31,Female,West,Marketing,125.90,Yes,Home Decor,Express
24,25,Emily Mitchell,27,Female,North,Designer,135.60,Yes,Books,Express
26,27,Avery Roberts,22,Female,West,Student,75.15,Yes,Home Decor,Express
28,29,Sofia Phillips,29,Female,North,Analyst,115.30,Yes,Books,Express
30,31,Grace Parker,26,Female,West,Marketing,140.40,Yes,Home Decor,Express
32,33,Madison Edwards,23,Female,North,Artist,90.50,Yes,Books,Express
34,35,Layla Stewart,30,Female,West,Teacher,120.70,Yes,Home Decor,Express
36,37,Zoey Reed,25,Female,North,Designer,130.95,Yes,Books,Express
38,39,Penelope Morgan,28,Female,West,Analyst,145.35,Yes,Home Decor,Express
40,41,Riley Brooks,24,Female,North,Student,80.15,Yes,Books,Express
42,43,Aria Bailey,27,Female,West,Marketing,135.65,Yes,Home Decor,Express
44,45,Hannah Cox,29,Female,North,Designer,125.80,Yes,Books,Express
46,47,Stella Butler,31,Female,West,Engineer,190.90,Yes,Electronics,Express
48,49,Natalie Fisher,26,Female,North,Artist,95.40,Yes,Books,Express
50,51,Victoria Gray,24,Female,West,Student,85.75,Yes,Home Decor,Express
52,53,Hazel West,28,Female,North,Marketing,140.15,Yes,Books,Express
54,55,Lillian Ford,30,Female,West,Teacher,120.25,Yes,Home Decor,Express
55,56,Aubrey Myers,27,Female,North,Designer,130.80,Yes,Books,Express
57,58,Ellie Long,23,Female,West,Student,75.90,Yes,Home Decor,Express
59,60,Arianna Price,26,Female,North,Analyst,145.15,Yes,Books,Express
61,62,Savannah Sanders,29,Female,West,Marketing,135.30,Yes,Home Decor,Express
63,64,Aurora Jenkins,24,Female,North,Artist,90.80,Yes,Books,Express
65,66,Skylar Ortiz,27,Female,West,Designer,125.95,Yes,Home Decor,Express
67,68,Clara Wells,30,Female,North,Analyst,140.65,Yes,Books,Express
69,70,Delilah Hayes,25,Female,West,Student,80.35,Yes,Home Decor,Express
71,72,Maya Hunter,28,Female,North,Marketing,135.40,Yes,Books,Express
73,74,Nora Hudson,26,Female,West,Designer,130.10,Yes,Home Decor,Express
75,76,Lydia Cole,24,Female,North,Artist,90.25,Yes,Books,Express
77,78,Eleanor Russell,29,Female,West,Teacher,120.45,Yes,Home Decor,Express
79,80,Aria Peterson,27,Female,North,Student,85.15,Yes,Books,Express
81,82,Lila Murray,25,Female,West,Marketing,140.25,Yes,Home Decor,Express
83,84,Addison Simmons,30,Female,North,Designer,130.70,Yes,Books,Express
85,86,Paisley Pierce,26,Female,West,Artist,95.50,Yes,Home Decor,Express
87,88,Autumn Ford,28,Female,North,Teacher,125.20,Yes,Books,Express
89,90,Brooklyn Dunn,24,Female,West,Student,80.90,Yes,Home Decor,Express
91,92,Audrey Fox,27,Female,North,Marketing,135.85,Yes,Books,Express
93,94,Piper Ellis,25,Female,West,Designer,130.95,Yes,Home Decor,Express
95,96,Aliyah Holmes,29,Female,North,Analyst,145.60,Yes,Books,Express
97,98,Sienna Riley,26,Female,West,Student,85.30,Yes,Home Decor,Express
99,100,Clara Dixon,28,Female,North,Artist,90.40,Yes,Books,Express

In [17]:
# 10. Select the first 5 columns for rows 10 to 20.
df.iloc[10:21,0:5]

    id    customer_name  age  gender region
10  11   Isabella Clark   30  Female   West
11  12   Noah Rodriguez   27    Male   East
12  13        Mia Lewis   34  Female  North
13  14     Ethan Walker   38    Male  South
14  15   Charlotte Hall   26  Female   West
15  16  Alexander Young   49    Male   East
16  17     Amelia Allen   21  Female  North
17  18      Daniel King   33    Male  South
18  19     Harper Scott   28  Female   West
19  20      Henry Green   44    Male   East
20  21     Evelyn Adams   24  Female  North

In [18]:
# 11. Select 'customer_name' and 'preferred_category' for customers with purchase_amount above 150.
df.loc[df["purchase_amount"]>150,["customer_name","preferred_category"]]

         customer_name preferred_category
0       Alice Thompson        Electronics
2           Emily Chen         Home Decor
3        Michael Patel        Electronics
5         James Wilson           Clothing
7       William Garcia        Electronics
9           Liam Davis           Clothing
11      Noah Rodriguez        Electronics
13        Ethan Walker           Clothing
15     Alexander Young        Electronics
18        Harper Scott        Electronics
19         Henry Green         Home Decor
21         Lucas Baker           Clothing
23         Jack Carter        Electronics
25      Benjamin Perez           Clothing
27        Mason Turner        Electronics
29     Elijah Campbell           Clothing
31         Logan Evans        Electronics
33       Aiden Collins           Clothing
35       Samuel Morris        Electronics
37          David Cook           Clothing
39         Joseph Bell        Electronics
41       Carter Cooper           Clothing
43         Owen Rivera        Electronics
45           Luke Ward           Clothing
46       Stella Butler        Electronics
47          Isaac Wood         Home Decor
49       Grayson Stone           Clothing
51       Julian Hughes        Electronics
53          Levi Perry           Clothing
56         Jaxon Kelly        Electronics
58      Lincoln Foster           Clothing
60      Connor Griffin        Electronics
62         Joshua Ross           Clothing
64  Christian Marshall        Electronics
66     Jeremiah Gordon           Clothing
68    Tristan Sullivan        Electronics
70       Eli Henderson           Clothing
72       Micah Andrews        Electronics
74        Aaron Bryant           Clothing
76       Isaiah Barnes        Electronics
78       Hudson Duncan           Clothing
80       Easton Jordan        Electronics
82           Ezra Reid           Clothing
84      Colton Freeman        Electronics
86          Evan Berry           Clothing
88         Nathan Hart        Electronics
90        Adrian Black           Clothing
92       Caleb Gardner        Electronics
94         Kayden Boyd           Clothing
96       Declan Porter        Electronics
98       Asher Wallace           Clothing

In [20]:
# 12. Select rows 40 to 50 and columns 'customer_name', 'gender', and 'delivery_preference' by their
# index positions.
df.iloc[40:51,[1,3,9]]

     customer_name  gender delivery_preference
40    Riley Brooks  Female             Express
41   Carter Cooper    Male            Standard
42     Aria Bailey  Female             Express
43     Owen Rivera    Male            Standard
44      Hannah Cox  Female             Express
45       Luke Ward    Male            Standard
46   Stella Butler  Female             Express
47      Isaac Wood    Male            Standard
48  Natalie Fisher  Female             Express
49   Grayson Stone    Male            Standard
50   Victoria Gray  Female             Express

In [24]:
# 13. Select all columns for customers aged 25 who prefer 'Books' as their category.
df.loc[(df["preferred_category"]=="Books") & (df["age"]==25),:]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
36,37,Zoey Reed,25,Female,North,Designer,130.95,Yes,Books,Express

In [25]:
# 14. Select the 6th column for the first 30 rows.
df.iloc[0:31,[6]]

    purchase_amount
0            150.75
1             89.50
2            220.30
3            175.20
4             65.10
5            300.80
6            120.45
7            200.60
8             95.25
9            180.90
10           140.70
11           160.35
12           110.15
13           250.40
14           130.85
15           280.95
16            70.20
17           145.65
18           190.50
19           210.25
20            85.30
21           170.80
22           125.90
23           155.45
24           135.60
25           230.75
26            75.15
27           195.20
28           115.30
29           270.85
30           140.40

In [27]:
# 15. Select 'customer_name', 'purchase_amount', and 'region' for customers with delivery_preference 'Express'.
df.loc[df["delivery_preference"]=="Express",["customer_name","purchase_amount","delivery_preference"]]

       customer_name  purchase_amount delivery_preference
0     Alice Thompson           150.75             Express
2         Emily Chen           220.30             Express
4      Sophia Nguyen            65.10             Express
6       Olivia Brown           120.45             Express
8       Ava Martinez            95.25             Express
10    Isabella Clark           140.70             Express
12         Mia Lewis           110.15             Express
14    Charlotte Hall           130.85             Express
16      Amelia Allen            70.20             Express
18      Harper Scott           190.50             Express
20      Evelyn Adams            85.30             Express
22    Abigail Nelson           125.90             Express
24    Emily Mitchell           135.60             Express
26     Avery Roberts            75.15             Express
28    Sofia Phillips           115.30             Express
30      Grace Parker           140.40             Express
32   Madison Edwards            90.50             Express
34     Layla Stewart           120.70             Express
36         Zoey Reed           130.95             Express
38   Penelope Morgan           145.35             Express
40      Riley Brooks            80.15             Express
42       Aria Bailey           135.65             Express
44        Hannah Cox           125.80             Express
46     Stella Butler           190.90             Express
48    Natalie Fisher            95.40             Express
50     Victoria Gray            85.75             Express
52        Hazel West           140.15             Express
54      Lillian Ford           120.25             Express
55      Aubrey Myers           130.80             Express
57        Ellie Long            75.90             Express
59     Arianna Price           145.15             Express
61  Savannah Sanders           135.30             Express
63    Aurora Jenkins            90.80             Express
65      Skylar Ortiz           125.95             Express
67       Clara Wells           140.65             Express
69     Delilah Hayes            80.35             Express
71       Maya Hunter           135.40             Express
73       Nora Hudson           130.10             Express
75        Lydia Cole            90.25             Express
77   Eleanor Russell           120.45             Express
79     Aria Peterson            85.15             Express
81       Lila Murray           140.25             Express
83   Addison Simmons           130.70             Express
85    Paisley Pierce            95.50             Express
87       Autumn Ford           125.20             Express
89     Brooklyn Dunn            80.90             Express
91        Audrey Fox           135.85             Express
93       Piper Ellis           130.95             Express
95     Aliyah Holmes           145.60             Express
97      Sienna Riley            85.30             Express
99       Clara Dixon            90.40             Express

In [28]:
# 16. Select rows 5, 15, 25, 35, and 45 and columns 1, 4, and 7.
df.iloc[[5,15,25,35,45],[1,4,7]]

      customer_name region loyalty_program
5      James Wilson  South              No
15  Alexander Young   East              No
25   Benjamin Perez  South              No
35    Samuel Morris   East              No
45        Luke Ward  South              No

In [5]:
# 17. Select all columns for customers whose names start with 'S'.
df.loc[df["customer_name"].str.startswith("S"),:]

,id,customer_name,age,gender,region,occupation,purchase_amount,loyalty_program,preferred_category,delivery_preference
4,5,Sophia Nguyen,19,Female,North,Student,65.10,Yes,Books,Express
28,29,Sofia Phillips,29,Female,North,Analyst,115.30,Yes,Books,Express
35,36,Samuel Morris,48,Male,East,Manager,240.80,No,Electronics,Standard
46,47,Stella Butler,31,Female,West,Engineer,190.90,Yes,Electronics,Express
61,62,Savannah Sanders,29,Female,West,Marketing,135.30,Yes,Home Decor,Express
65,66,Skylar Ortiz,27,Female,West,Designer,125.95,Yes,Home Decor,Express
97,98,Sienna Riley,26,Female,West,Student,85.30,Yes,Home Decor,Express

In [51]:
# 18. Select the last 8 rows and the first 3 columns.
df.iloc[-8,0:3]

id                          93
customer_name    Caleb Gardner
age                         45
Name: 92, dtype: object

In [44]:
# 19. Select 'customer_name' and 'purchase_amount' for customers with purchase_amount between
# 100 and 200 (inclusive).
df.loc[df["purchase_amount"].between(100,200),["customer_name","purchase_amount"]]

       customer_name  purchase_amount
0     Alice Thompson           150.75
3      Michael Patel           175.20
6       Olivia Brown           120.45
9         Liam Davis           180.90
10    Isabella Clark           140.70
11    Noah Rodriguez           160.35
12         Mia Lewis           110.15
14    Charlotte Hall           130.85
17       Daniel King           145.65
18      Harper Scott           190.50
21       Lucas Baker           170.80
22    Abigail Nelson           125.90
23       Jack Carter           155.45
24    Emily Mitchell           135.60
27      Mason Turner           195.20
28    Sofia Phillips           115.30
30      Grace Parker           140.40
33     Aiden Collins           165.25
34     Layla Stewart           120.70
36         Zoey Reed           130.95
37        David Cook           185.10
38   Penelope Morgan           145.35
42       Aria Bailey           135.65
43       Owen Rivera           160.30
44        Hannah Cox           125.80
45         Luke Ward           170.45
46     Stella Butler           190.90
49     Grayson Stone           150.60
52        Hazel West           140.15
53        Levi Perry           195.50
54      Lillian Ford           120.25
55      Aubrey Myers           130.80
58    Lincoln Foster           175.60
59     Arianna Price           145.15
61  Savannah Sanders           135.30
62       Joshua Ross           190.25
65      Skylar Ortiz           125.95
66   Jeremiah Gordon           160.50
67       Clara Wells           140.65
70     Eli Henderson           170.85
71       Maya Hunter           135.40
73       Nora Hudson           130.10
74      Aaron Bryant           195.30
77   Eleanor Russell           120.45
78     Hudson Duncan           150.80
81       Lila Murray           140.25
82         Ezra Reid           175.35
83   Addison Simmons           130.70
86        Evan Berry           190.65
87       Autumn Ford           125.20
91        Audrey Fox           135.85
93       Piper Ellis           130.95
94       Kayden Boyd           170.50
95     Aliyah Holmes           145.60
96     Declan Porter           195.25
98     Asher Wallace           160.75

In [45]:
# 20. Select every 4th row from 0 to 60 and columns 3, 6, and 9.
df.iloc[0:60:4,[3,6,9]]

    gender  purchase_amount delivery_preference
0   Female           150.75             Express
4   Female            65.10             Express
8   Female            95.25             Express
12  Female           110.15             Express
16  Female            70.20             Express
20  Female            85.30             Express
24  Female           135.60             Express
28  Female           115.30             Express
32  Female            90.50             Express
36  Female           130.95             Express
40  Female            80.15             Express
44  Female           125.80             Express
48  Female            95.40             Express
52  Female           140.15             Express
56    Male           215.45            Standard

In [47]:
# 21. Select 'customer_name', 'occupation', and 'loyalty_program' for customers aged between 20 and 30 (inclusive).
df.loc[(df["age"]>=20) & (df["age"]<=30),['customer_name', 'occupation','loyalty_program']]

       customer_name occupation loyalty_program
0     Alice Thompson   Engineer             Yes
2         Emily Chen   Designer             Yes
6       Olivia Brown    Analyst             Yes
8       Ava Martinez     Artist             Yes
10    Isabella Clark  Marketing             Yes
11    Noah Rodriguez   Engineer              No
14    Charlotte Hall   Designer             Yes
16      Amelia Allen    Student             Yes
18      Harper Scott   Engineer             Yes
20      Evelyn Adams     Artist             Yes
24    Emily Mitchell   Designer             Yes
26     Avery Roberts    Student             Yes
28    Sofia Phillips    Analyst             Yes
30      Grace Parker  Marketing             Yes
32   Madison Edwards     Artist             Yes
34     Layla Stewart    Teacher             Yes
36         Zoey Reed   Designer             Yes
38   Penelope Morgan    Analyst             Yes
40      Riley Brooks    Student             Yes
42       Aria Bailey  Marketing             Yes
44        Hannah Cox   Designer             Yes
48    Natalie Fisher     Artist             Yes
50     Victoria Gray    Student             Yes
52        Hazel West  Marketing             Yes
54      Lillian Ford    Teacher             Yes
55      Aubrey Myers   Designer             Yes
57        Ellie Long    Student             Yes
59     Arianna Price    Analyst             Yes
61  Savannah Sanders  Marketing             Yes
63    Aurora Jenkins     Artist             Yes
65      Skylar Ortiz   Designer             Yes
67       Clara Wells    Analyst             Yes
69     Delilah Hayes    Student             Yes
71       Maya Hunter  Marketing             Yes
73       Nora Hudson   Designer             Yes
75        Lydia Cole     Artist             Yes
77   Eleanor Russell    Teacher             Yes
79     Aria Peterson    Student             Yes
81       Lila Murray  Marketing             Yes
83   Addison Simmons   Designer             Yes
85    Paisley Pierce     Artist             Yes
87       Autumn Ford    Teacher             Yes
89     Brooklyn Dunn    Student             Yes
91        Audrey Fox  Marketing             Yes
93       Piper Ellis   Designer             Yes
95     Aliyah Holmes    Analyst             Yes
97      Sienna Riley    Student             Yes
99       Clara Dixon     Artist             Yes

In [48]:
# 22. Select rows 60 to 70 and the columns corresponding to 'age', 'region', and 'preferred_category'.
df.loc[60:70,['age', 'region','preferred_category']]

    age region preferred_category
60   41  South        Electronics
61   29   West         Home Decor
62   36   East           Clothing
63   24  North              Books
64   48  South        Electronics
65   27   West         Home Decor
66   35   East           Clothing
67   30  North              Books
68   42  South        Electronics
69   25   West         Home Decor
70   39   East           Clothing

In [49]:
# 23. Select all columns for customers in the East region with purchase_amount less than 150.
df.loc[(df["region"]=="East") & (df["purchase_amount"]<150),:]

Empty DataFrame
Columns: [id, customer_name, age, gender, region, occupation, purchase_amount, loyalty_program, preferred_category, delivery_preference]
Index: []

In [50]:
# 24. Select the first 12 rows and the last 3 columns.
df.iloc[0:12,-3]

0     Yes
1      No
2     Yes
3      No
4     Yes
5      No
6     Yes
7      No
8     Yes
9      No
10    Yes
11     No
Name: loyalty_program, dtype: object

In [54]:
# 25. Select 'customer_name', 'age', and 'delivery_preference' for customers with id in the range 30 to 50.
df.loc[(df["id"].between(30,50)),['customer_name', 'age', 'delivery_preference']]

      customer_name  age delivery_preference
29  Elijah Campbell   40            Standard
30     Grace Parker   26             Express
31      Logan Evans   43            Standard
32  Madison Edwards   23             Express
33    Aiden Collins   37            Standard
34    Layla Stewart   30             Express
35    Samuel Morris   48            Standard
36        Zoey Reed   25             Express
37       David Cook   34            Standard
38  Penelope Morgan   28             Express
39      Joseph Bell   41            Standard
40     Riley Brooks   24             Express
41    Carter Cooper   39            Standard
42      Aria Bailey   27             Express
43      Owen Rivera   45            Standard
44       Hannah Cox   29             Express
45        Luke Ward   36            Standard
46    Stella Butler   31             Express
47       Isaac Wood   42            Standard
48   Natalie Fisher   26             Express
49    Grayson Stone   38            Standard